version: "3.8"
services:
  postgres_local:
    container_name: postgres_local
    restart: always
    image: postgres:13.1
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_volume:/var/lib/postgresql/data

  redis_local:
    image: redis:6.2-alpine
    container_name: redis_local
    restart: always
    ports:
      - '9736:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis_volume:/data

  rahat_local:
    depends_on:
      - postgres_local
      - redis_local
    container_name: rahat_local
    image: rahat_local_image
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules 
      - /usr/src/app/.nx
    env_file:
      - .env
    ports:
      - 5500:5500
    restart: always
    entrypoint: sh ./tools/docker-scripts/init-rahat.sh

  beneficiary_local:
    depends_on:
      - postgres_local
      - redis_local
      - rahat_local
    container_name: beneficiary_local
    image: beneficiary_local_image
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules 
      - /usr/src/app/.nx
    env_file:
      - .env
    restart: always
    entrypoint: sh ./tools/docker-scripts/init-beneficiary.sh

volumes:
  pg_volume:
  redis_volume:

networks:
  default:
    name: rahat_network
    external: true
    