version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${NAME}
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ./data/rahat/postgres:/var/lib/postgresql/data
      - ./data/dropbox:/dropbox
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: "pgadmin"
    volumes:
      - ./data/rahat/pgadmin:/var/lib/pgadmin
      - ./data/dropbox:/dropbox
    environment:
      - PGADMIN_DEFAULT_EMAIL=${EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
  dropbox:
    image: rumsan/santosh-dropbox:latest
    container_name: dropbox
    restart: always
    # env_file:
    #   - .dropbox.env
    environment:
      - NAME=${NAME}
      - PORT=${DROPBOX_PORT}
    ports:
      - "${DROPBOX_PORT}:${DROPBOX_PORT}"
    volumes:
      - ./data/dropbox:/dropbox
  # ganache:
  #   image: rumsan/santosh-ganache
  #   platform: linux/amd64
  #   container_name: ganache
  #   restart: always
  #   environment:
  #     - PORT=${GANACHE_PORT}
  #     - MNEMONIC=${MNEMONIC}
  #     - DB_PATH=/db
  #     - ETH_BALANCE=1000000000
  #     - RS_TUNNEL=${NAME}-ganache
  #   ports:
  #     - "${GANACHE_PORT}:8545"
  #   volumes:
  #     - ./data/volumes/ganache:/db
  #     - ./data/dropbox:/dropbox
  #   networks:
  #     - default_network

  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${PASSWORD}
    volumes:
      - ./data/rahat/redis:/data
  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - "${BULLBOARD_PORT}:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ${PASSWORD}
    depends_on:
      - redis
networks:
  default_network:
    driver: bridge
