version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${NAME}
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ./data/rahat/postgres:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: "pgadmin"
    volumes:
      - ./data/rahat/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

  ganache:
    image: trufflesuite/ganache
    platform: linux/amd64
    container_name: "ganache"
    command: --accounts 20 -m "${MNEMONIC}" --database.dbPath "/db" --logging.file /db/ganache.log --miner.blockTime 2 --chain.networkId "${GANACHE_PORT}" --chain.chainId "${GANACHE_PORT}" --chain.asyncRequestProcessing true
    restart: always
    ports:
      - "${GANACHE_PORT}:8545"
    volumes:
      - ./data/ganache:/db
    networks:
      - default_network

  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${PASSWORD}
    volumes:
      - ./data/rahat/redis:/data

  bullboard:
    container_name: bullboard
    platform: linux/amd64
    image: deadly0/bull-board
    restart: always
    ports:
      - "${BULLBOARD_PORT}:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ${PASSWORD}
    depends_on:
      - redis

networks:
  default_network:
    driver: bridge
