name: Dev Root CD/CD
on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

env:
  CI: false
  env_dev: ${{ secrets.ENV_DEV }}
  BENEFICIARY_IMAGE_TAG: esatya/beneficiary:dev
  RAHAT_IMAGE_TAG: esatya/rahat:dev

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: import env file
        run: |
          touch ./.env && echo "$env_dev" >> ./.env

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run api:app:generate
          pnpm run api:news:generate
          pnpm build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Beneficiary Image
      - name: build && push beneficiary
        id: build-push-beneficiary
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.beneficiary
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: $BENEFICIARY_IMAGE_TAG

      # Rahat Image
      - name: build && push rahat
        id: build-push-rahat
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.rahat
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: $RAHAT_IMAGE_TAG
